version: '{build}-{branch}'
image: Visual Studio 2017

init:
  # Disable Hyper-V
  - ps: Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All
  - ps: mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    # Disable chocolatey´s verbose download output
  - choco feature disable --name showDownloadProgress
  - choco install virtualbox --yes
  #- choco install vagrant --yes

install:
  - ps: Start-FileDownload "https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.msi"
  - ps: Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_2.2.1_x86_64.msi /qb TARGETDIR=C:\Vagrant" -Wait
  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
  # Vagrant correctly installed?
  - vagrant --version
  - ssh -V
  - ipconfig /all

build_script:
  - ps: Test-NetConnection google.com -Port 80
  - vagrant up
  - vagrant ssh -c "echo 'hello world!'"
  #|| ssh vagrant@127.0.0.1 -p 2222 -i .vagrant\machines\default\virtualbox\private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv -C "pwd"
  #- vagrant ssh -c "uname -a"

test: off
#test_script:
#  - ansible-playbook playbook.yml -i hosts --syntax-check